name: Module 7 Workflow

on: [push]

jobs:
  web:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: new_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U myuser" --health-interval

    env:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/new_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run application
        run: |
          uvicorn main:app --host 0.0.0.0